version: "3.9"

services:
  mysql:
    image: mysql:8.0

    container_name: weather_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather_api

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  weather_etl:
    build: .

    container_name: weather_etl

    depends_on:
      - mysql

    env_file:
      - .env

volumes:
  mysql_data:
